spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: erpbooks1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-raff3lhzvccgz05a.us.auth0.com/
          audience: https://user-api
        

server:
  port: 9010
  servlet:
    context-path: /erp
    
cron:
  expression: 0/30 * * * * *

logging:
  level:
    root: INFO
    com:
      example:
        erpdemo: DEBUG
  file:
    name: logs/app.log
    max-history: 30
    max-size: 10MB

  
#issuer-uri: https://dev-raff3lhzvccgz05a.us.auth0.com/
# audience: https://user-api


# issuer-uri: https://mps-dev.auth0.com/
#           audience: mps-dev-api